thrift/lib/cpp2/protocol/JSONProtocolCommon.cpp: fix llvm-21-exposed -Wcharacter-conversion warning
Summary:
This avoids the following errors:

```
$ buck test -m llvmfb21 -c cxx.extra_cxxflags=-Wno-missing-noreturn biggrep/...
...
fbcode/thrift/lib/cpp2/protocol/JSONProtocolCommon.cpp:151:10: error: implicit conversion from 'char16_t' to 'char32_t' may change the meaning of the represented code unit [-Werror,-Wcharacter-conversion]
  151 |     cp = c0;
      |        ~ ^~
1 error generated.
Action failed: fbcode//thrift/lib/cpp2/protocol:json_protocol_common (cxx_compile JSONProtocolCommon.cpp (pic) (optimized))
```

Reviewed By: dtolnay

Differential Revision: D88647803

fbshipit-source-id: 67fb3931e526b3e10d4fa859b34bedc17cdc5673