Fix name collision in generated C++ code
Summary:
Thrift may generate invalid C++ code for fields named `T` because of a name collision with a template argument. Previously compilers were not diagnosing it but newer version of clang makes it an error by default which already shows up in macOS builds and will eventually show up on Linux once the toolchain is updated. Fix it via the usual method of adding the `fbthrift_` prefix. In C++20 we could probably get rid of it by using `auto`.

We already have a test for this sort of collisions which is currently failing:

```
$ buck build mode/mac-arm64 thrift/test/reflection/...
File changed: fbsource//xplat/thrift/compiler/generate/templates/cpp2/module_types_h
File changed: fbsource//xplat/thrift/compiler/generate/templates
File changed: fbsource//xplat/thrift/compiler/generate
5 additional file change events
Action failed: fbcode//thrift/test/reflection:regression_if-cpp2-types (cxx_compile gen-cpp2/regression_data.cpp (pi
c))
Remote command returned non-zero exit code 1
Reproduce locally: `frecli cas download-action f86835a5dbc3e19839ab2be6683353065f4f6fb7113d19068671b80faf65c3ac:145`
stdout:
stderr:
In file included from buck-out/v2/gen/fbcode/55133eca1aa350b7/thrift/test/reflection/__regression_if-cpp2-regression
.thrift__/out/gen-cpp2/regression_data.cpp:8:
In file included from buck-out/v2/gen/fbcode/55133eca1aa350b7/thrift/test/reflection/__regression_if-cpp2-regression
.thrift__/out/gen-cpp2/regression_data.h:11:
buck-out/v2/gen/fbcode/55133eca1aa350b7/thrift/test/reflection/__regression_if-cpp2-regression.thrift__/out/gen-cpp2
/regression_types.h:295:53: error: declaration of 'T' shadows template parameter [-Wstrict-primary-template-shadow]
  295 |   FOLLY_ERASE ::apache::thrift::field_ref<const T&> T() const& {
      |                                                     ^
buck-out/v2/gen/fbcode/55133eca1aa350b7/thrift/test/reflection/__regression_if-cpp2-regression.thrift__/out/gen-cpp2
/regression_types.h:294:35: note: template parameter is declared here
  294 |   template <typename..., typename T = ::std::int32_t>
      |                                   ^
buck-out/v2/gen/fbcode/55133eca1aa350b7/thrift/test/reflection/__regression_if-cpp2-regression.thrift__/out/gen-cpp2
/regression_types.h:301:54: error: declaration of 'T' shadows template parameter [-Wstrict-primary-template-shadow]
  301 |   FOLLY_ERASE ::apache::thrift::field_ref<const T&&> T() const&& {
      |                                                      ^
buck-out/v2/gen/fbcode/55133eca1aa350b7/thrift/test/reflection/__regression_if-cpp2-regression.thrift__/out/gen-cpp2
/regression_types.h:300:35: note: template parameter is declared here
  300 |   template <typename..., typename T = ::std::int32_t>
      |                                   ^
...
```

Reviewed By: sadroeck

Differential Revision: D71978343

fbshipit-source-id: eab4dd45d6f845c573d1d12f2a6f7b5147a1e29c