Fix RocketClient build under some versions of gcc
Summary:
[Thrift] Fix RocketClient build under some versions of gcc, which require extra `this->`'s.

```
thrift/lib/cpp2/transport/rocket/client/RocketClient.cpp:171:71: error: cannot call member function ‘apache::thrift::rocket::StreamChannelStatus apache::thrift::rocket::RocketClient::handlePayloadFrame(CallbackType&, std::unique_ptr<folly::IOBuf>) [with CallbackType = apache::thrift::rocket::RocketSinkServerCallback]’ without object
             return handlePayloadFrame(serverCallback, std::move(frame));
                                                                       ^
thrift/lib/cpp2/transport/rocket/client/RocketClient.cpp:173:69: error: cannot call member function ‘apache::thrift::rocket::StreamChannelStatus apache::thrift::rocket::RocketClient::handleErrorFrame(CallbackType&, std::unique_ptr<folly::IOBuf>) [with CallbackType = apache::thrift::rocket::RocketSinkServerCallback]’ without object
             return handleErrorFrame(serverCallback, std::move(frame));
                                                                     ^
thrift/lib/cpp2/transport/rocket/client/RocketClient.cpp:175:72: error: cannot call member function ‘apache::thrift::rocket::StreamChannelStatus apache::thrift::rocket::RocketClient::handleRequestNFrame(CallbackType&, std::unique_ptr<folly::IOBuf>) [with CallbackType = apache::thrift::rocket::RocketSinkServerCallback]’ without object
             return handleRequestNFrame(serverCallback, std::move(frame));
                                                                        ^
thrift/lib/cpp2/transport/rocket/client/RocketClient.cpp:177:70: error: cannot call member function ‘apache::thrift::rocket::StreamChannelStatus apache::thrift::rocket::RocketClient::handleCancelFrame(CallbackType&, std::unique_ptr<folly::IOBuf>) [with CallbackType = apache::thrift::rocket::RocketSinkServerCallback]’ without object
             return handleCancelFrame(serverCallback, std::move(frame));
                                                                      ^
thrift/lib/cpp2/transport/rocket/client/RocketClient.cpp:179:18: error: cannot call member function ‘void apache::thrift::rocket::RocketClient::close(folly::exception_wrapper)’ without object
             close(folly::make_exception_wrapper<transport::TTransportException>(
                  ^
```

Reviewed By: andriigrynenko

Differential Revision: D16514002

fbshipit-source-id: 9190ee3196c882c42e2aba14b6cf0fec09bf63db