work around compile error affecting ServerStreamGenerator under MSVC
Summary:
The member function `ServerStreamGenerator::fromAsyncGenerator` has a coroutine lambda nested within a lambda nested within a lambda. Some versions of MSVC appear unable to handle this case.

```
thrift\lib\cpp2\async\ServerGeneratorStream-inl.h(35): error C7617: 'apache::thrift::detail::ServerGeneratorStream::fromAsyncGenerator::<lambda_1>::()::<lambda_1>::operator ()': A coroutine cannot have a return type containing 'auto'
```

The implication is that the compiler transfers the inference that the innermost lambda is a coroutine since it contains a coroutine keyword onto a surrounding lambda, which is not a coroutine. Coroutine lambdas must declare non-`auto` return types, but non-coroutine lambdas are free to omit return types.

Work around this problem by extracting the nested-nested-lambda to its own coroutine function.

Reviewed By: trandi

Differential Revision: D53866145

fbshipit-source-id: 86cf842ecec493dfef6f5f0f2081b0c3b5500880