thrift: avoid compilation failure due to use of undefined CHECK macro
Summary:
[FYI, I stumbled across this when trying to test upcoming remove of
all g_..._constants definitions. ]

One of thrift's files used CHECK without including glob/logging.h.
Include it, to avoid these errors:

thrift/test/TFileTransportTest.cpp: In member function 'void FsyncTimer::checkResults() const':
thrift/test/TFileTransportTest.cpp:127:28: error: 'CHECK' was not declared in this scope
thrift/test/TFileTransportTest.cpp: In function 'void test_flush_max_us_impl(uint32_t, uint32_t, uint32_t)':
thrift/test/TFileTransportTest.cpp:306:31: error: 'CHECK' was not declared in this scope

Test Plan:
fbconfig -r thrift && fbmake dev

Reviewed By: sugak@fb.com

Subscribers: net-systems@, alandau, dancol, yfeldblum

FB internal diff: D2186051

Signature: t1:2186051:1435121392:5750bce80723b123c7b55482884a67a3eae893c0