Resolve name conflict on services with snake case name
Summary:
Previously the generated code for Thrift client mocks looked like:

```
pub mod mock {
    // for each service:
    pub struct {{service:name}} {...}
    mod {{service:snake}} {...}
}
```

where for example {{service:name}} is `BaseService` and {{service:snake}} is `base_service`. But a name conflict arises when services are named (unidiomatically?) lowercase, as seen in:

https://www.internalfb.com/intern/diffusion/FBS/browsefile/master/fbcode/fbagent/if/fbagent.thrift?commit=944dfaf81a7b4c13199c6afcaab13caa24772f2e&lines=173

```
error[E0428]: the name `fbagent` is defined multiple times
    --> buck-out/dev/gen/fbagent/if/fbagent-rust-fbagent.thrift=gen-rust/lib.rs/gen-rust/lib.rs:4947:5
     |
4768 |     pub struct fbagent<'mock> {
     |     ------------------------- previous definition of the type `fbagent` here
...
4947 |     mod fbagent {
     |     ^^^^^^^^^^^ `fbagent` redefined here
     |
     = note: `fbagent` must be defined only once in the type namespace of this module
```

This diff moves the private implementation detail module out of the module containing the public struct to avoid such conflicts.

```
pub mod mock {
    // for each service:
    pub struct {{service:name}} {...}

    mod r#impl {
        // for each service:
        pub(super) mod {{service:snake}} {...}
    }
}
```

Reviewed By: jsgf

Differential Revision: D22368791

fbshipit-source-id: fd39102a4e574c80e5789384be175ce3a807203c