Conditionally depend on sinit header
Summary:
This breaks some exotic build configs without stdlib headers:
```
fbcode/folly/detail/FileUtilDetail.cpp:17:10: fatal error: 'cassert' file not found
   17 | #include <cassert>
```

Reviewed By: vitaut

Differential Revision: D59926352

fbshipit-source-id: b3f30351009743274463f9283d0fdbd7cdf0bb76