Disable Cargo documentation generation for Thrift targets
Summary:
I came across this failure in `oss-mononoke-linux-getdeps` likely caused by {D53302058}:

> error: document output filename collision
> The lib `bonsai_globalrev_mapping_thrift` in package `bonsai_globalrev_mapping_thrift_types v0.1.0 (/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/build/mononoke/source/eden/mononoke/bonsai_globalrev_mapping/if/types)` has the same name as the lib `bonsai_globalrev_mapping_thrift` in package `bonsai_globalrev_mapping_thrift v0.1.0 (/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/build/mononoke/source/eden/mononoke/bonsai_globalrev_mapping/if)`.
> Only one may be documented at once since they output to the same path.
> Consider documenting only one, renaming one, or marking one with `doc = false` in Cargo.toml.

We don't need Cargo-generated docs of Thrift targets.

Reviewed By: zertosh

Differential Revision: D53339579

fbshipit-source-id: 3dc0d404777ca436e0f6de7ae7491925d709e331