Generate *Exn with full return type for streaming methods
Summary:
**Update:** I have opted out the whole (de)-serialization stuff in case of streaming methods. Consequently, I am returning an error in case of streaming methods in the following diff  D37584509. However, I am pushing this and the following diff for review, as I think we can build on top of these changes to support streaming returns.

`service.mustache` defines different enum types for each API service that contain the success value and exception types. These enums are suffixed with `Exn`, as per the convention mentioned [here](https://www.internalfb.com/code/fbsource/[180a1a2a3993]/fbcode/thrift/lib/rust/src/exceptions.rs?lines=35-39), although I think the style is confusing for a new reader ( a better suffix would be *Result? ).

Previously, there were two `Exn`s for streaming method, one for the stream return, suffixed with `StreamExn`, and one for the response return, suffixed with just `Exn`. These two were consumed by the clients when capturing the two types of returns ( success or error ).

This diff has changed the suffix of the response from just `Exn` to `ResponseExn`. For the ones with just the `Exn` suffix, the success value now contains the full return type (response, if present, and stream), similar to non-streaming methods. We will require this `*Exn` in the following diff D37584509, where we receive the output from the user code, and cast it into an `*Exn` type.

However, the missing puzzle is serialization and deserialization.
First, I can not impl `Debug` for `*Exn` type with streaming responses. The error I get is:
```

error[E0277]: `(dyn futures::Stream<Item = Result<std::string::String, NonthrowingFunctionError>> + std::marker::Send + 'static)` doesn't implement `Debug`
    --> scripts/nasifimtiaz/thrift/lib.rs:1586:21
     |
1583 | ...Clone, Debug)]
     |           ----- in this derive macro expansion
```
For now, I have opted out of `Debug` trait if the `*Exn` contains a stream. However, the `Exn` type also implements `::fbthrift::Serialize<P>` and `::fbthrift::Deserialize<P>` for the success types, which fail as well. I get the below errors:

```
error[E0599]: the method `write` exists for reference `&Pin<Box<(dyn futures::Stream<Item = Result<MultResponse, NonthrowingFunctionError>> + std::marker::Send + 'static)>>`, but its trait bounds were not satisfied
   --> scripts/nasifimtiaz/thrift/lib.rs:443:31
    |
443 |                           inner.write(p);
    |                                 ^^^^^ method cannot be called on `&Pin<Box<(dyn futures::Stream<Item = Result<MultResponse, NonthrowingFunctionError>> + std::marker::Send + 'static)>>` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `Pin<Box<dyn futures::Stream<Item = Result<MultResponse, NonthrowingFunctionError>> + std::marker::Send>>: Serialize<_>`
            which is required by `&Pin<Box<dyn futures::Stream<Item = Result<MultResponse, NonthrowingFunctionError>> + std::marker::Send>>: Serialize<_>
```

```
error[E0277]: the trait bound `(i32, Pin<Box<dyn futures::Stream<Item = Result<std::string::String, GetResponseAndStreamWithStreamNServiceExceptionStreamError>> + std::marker::Send>>): Deserialize<P>` is not satisfied
    --> scripts/nasifimtiaz/thrift/lib.rs:2139:123
     |
2139 | ...mWithStreamNServiceExceptionExn::Success(::fbthrift::Deserialize::read(p)?));
     |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Deserialize<P>` is not implemented for `(i32, Pin<Box<dyn futures::Stream<Item = Result<std::string::String, GetResponseAndStreamWithStreamNServiceExceptionStreamError>> + std::marker::Send>>)`
     |
     = help: the following implementations were found:
               <() as Deserialize<P>>
```

For now, I have excluded these two lines in case of streaming methods. As you can see in the error, the issue is that `::fbthrift::ProtocolWriter` and `::fbthrift::ProtocolReader` do not support stream type.

At this point, I can think of **multiple ways**:

-  Implementing serialization for streams in [rust protocol](https://www.internalfb.com/code/fbsource/[c24527517d592d294906cd5e108e48380998104b]/fbcode/thrift/lib/rust/src/serialize.rs). Specifically, making [this](https://www.internalfb.com/code/fbsource/[a531d7bd1f04]/fbcode/thrift/lib/rust/src/protocol.rs?lines=189) work:
```
TType::Stream => bail_err!(ProtocolError::StreamUnsupported),
```
 Stream type has also been listed [here](https://www.internalfb.com/code/fbsource/[a531d7bd1f04]/fbcode/thrift/lib/rust/src/ttype.rs). If this approach makes sense, it should make everything else going forward much easier. ( Should it also make Debug work? )

- Add new trait method `call_stream` [here](https://www.internalfb.com/code/fbsource/[a531d7bd1f04]/fbcode/thrift/lib/rust/src/processor.rs?lines=41), and implement that in `server.mustache`. However, that'd also mean adding `handle_stream_method` as well. We will also need to add logic to invoke the right handler (`handle_method` or `handle_stream_method`), preferably ~~judging from the request metadata~~ in the mustache template which has ``{{function:returns_stream?}}` parsed from the IDL file. In that case, this method's return type will emulate the streaming return with each item being encoded:
```
Result<(FramingEncodedFinal<F>,Pin<Box<dyn future<Stream<Item= FramingEncodedFinal<F>, Error>>>), Error>
```
The intuition for this design comes from [client-side streaming](https://www.internalfb.com/code/fbsource/[a531d7bd1f04]/fbcode/thrift/lib/rust/src/client.rs?lines=61-62).

- Implement `Debug` for streaming outputs in `service.mustache`. Basically, we would add serialization logic within the generated code for the `*Exn` types that contain streams. We might also need to add some code in the `handle_X` method in `server.mustache` as well.

Let me know which do you think is the best way moving forward?

Reviewed By: wqfish

Differential Revision: D37582884

fbshipit-source-id: 66a8e0e8f6c5d4826aae8f98033ae6a580f8a38b