thrift: fix cycle in cmake build graph
Summary:
This commit fixes a linker error that manifests in the watchman build:

```
/data/users/wez/scratch/dataZusersZwezZfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/librpcmetadata.a(RpcMetadata_types.cpp.o): In function `apache::thrift::detail::TccStructTraits<apache::thrift::CodecConfig>::translateFieldName(folly::Range<char const*>, short&, apache::thrift::protocol::TType&)':
/data/users/wez/scratch/dataZusersZwezZfbsource/fbcode_builder_getdeps/build/fbthrift/thrift/lib/thrift/gen-cpp2/RpcMetadata_types.cpp:415: undefined reference to `apache::thrift::detail::st::translate_field_name(folly::Range<char const*>, short&, apache::thrift::protocol::TType&, apache::thrift::detail::st::translate_field_name_table const&)'
/data/users/wez/scratch/dataZusersZwezZfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/librpcmetadata.a(RpcMetadata_types.cpp.o): In function `apache::thrift::detail::TccStructTraits<apache::thrift::CompressionConfig>::translateFieldName(folly::Range<char const*>, short&, apache::thrift::protocol::TType&)':
/data/users/wez/scratch/dataZusersZwezZfbsource/fbcode_builder_getdeps/build/fbthrift/thrift/lib/thrift/gen-cpp2/RpcMetadata_types.cpp:558: undefined reference to `apache::thrift::detail::st::translate_field_name(folly::Range<char const*>, short&, apache::thrift::protocol::TType&, apache::thrift::detail::st::translate_field_name_table const&)'
/data/users/wez/scratch/dataZusersZwezZfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/librpcmetadata.a(RpcMetadata_types.cpp.o): In function `apache::thrift::detail::TccStructTraits<apache::thrift::NegotiationParameters>::translateFieldName(folly::Range<char const*>, short&, apache::thrift::protocol::TType&)':
/data/users/wez/scratch/dataZusersZwezZfbsource/fbcode_builder_getdeps/build/fbthrift/thrift/lib/thrift/gen-cpp2/RpcMetadata_types.cpp:673: undefined reference to `apache::thrift::detail::st::translate_field_name(folly::Range<char const*>, short&, apache::thrift::protocol::TType&, apache::thrift::detail::st::translate_field_name_table const&)'
/data/users/wez/scratch/dataZusersZwezZfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/librpcmetadata.a(RpcMetadata_types.cpp.o): In function `apache::thrift::detail::TccStructTraits<apache::thrift::InteractionCreate>::translateFieldName(folly::Range<char const*>, short&, apache::thrift::protocol::TType&)':
/data/users/wez/scratch/dataZusersZwezZfbsource/fbcode_builder_getdeps/build/fbthrift/thrift/lib/thrift/gen-cpp2/RpcMetadata_types.cpp:761: undefined reference to `apache::thrift::detail::st::translate_field_name(folly::Range<char const*>, short&, apache::thrift::protocol::TType&, apache::thrift::detail::st::translate_field_name_table const&)'
/data/users/wez/scratch/dataZusersZwezZfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/librpcmetadata.a(RpcMetadata_types.cpp.o): In function `apache::thrift::detail::TccStructTraits<apache::thrift::InteractionTerminate>::translateFieldName(folly::Range<char const*>, short&, apache::thrift::protocol::TType&)':
/data/users/wez/scratch/dataZusersZwezZfbsource/fbcode_builder_getdeps/build/fbthrift/thrift/lib/thrift/gen-cpp2/RpcMetadata_types.cpp:856: undefined reference to `apache::thrift::detail::st::translate_field_name(folly::Range<char const*>, short&, apache::thrift::protocol::TType&, apache::thrift::detail::st::translate_field_name_table const&)'
/data/users/wez/scratch/dataZusersZwezZfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/librpcmetadata.a(RpcMetadata_types.cpp.o):/data/users/wez/scratch/dataZusersZwezZfbsource/fbcode_builder_getdeps/build/fbthrift/thrift/lib/thrift/gen-cpp2/RpcMetadata_types.cpp:989: more undefined references to `apache::thrift::detail::st::translate_field_name(folly::Range<char const*>, short&, apache::thrift::protocol::TType&, apache::thrift::detail::st::translate_field_name_table const&)' follow
collect2: error: ld returned 1 exit status
```

In the cmake build, `thriftcpp2` depends on `rpcmetadata`.
From the above errors, `rpcmetadata` indirectly references the `translate_field_name_table` added in D23420408 (https://github.com/facebook/fbthrift/commit/ad2746eb2fb2284924191a3d3b888c9e1b999ccc) to the `thriftcpp2` target.
Therefore, moving `gen/module_types_cpp.cpp` from `thriftcpp2` to `rpcmetadata` resolves the dependency cycle.

Reviewed By: Mizuchi

Differential Revision: D23785261

fbshipit-source-id: 4416b8bbbc25d0aa351cdca371349dc2c6bc666e