Use standard gflags in conformance
Summary:
`folly/portability:gflags` is neither portable nor needed. Switch to standard gflags in conformance to fix errors of the form:

```
In file included from xplat/thrift/conformance/stresstest/util/IoUringUtil.cpp:17:
xplat/thrift/conformance/stresstest/util/IoUringUtil.h:22:1: error: unknown type name 'DECLARE_bool'
   22 | DECLARE_bool(use_iouring_event_eventfd);
      | ^
```

Reviewed By: iahs, yoney

Differential Revision: D77742799

fbshipit-source-id: 4cfe7adedb30e60d6afbbff50c5d894752421ef3