fix some gcc-5 build errors
Summary:
Call `std::ostringstream::str` to fix:
```
thrift/test/cpp/src/TestServer.cpp:450:10: error: no match for 'operator<<' (operand types are 'std::ostream {aka std::basic_ostream<char>}' and 'std::ostringstream {aka std::__cxx1
1::basic_ostringstream<char>}')
```
Add missing #include to fix:
```
thrift/test/TransportTest.cpp:81:3: error: 'mt19937' does not name a type
thrift/test/TransportTest.cpp:71:47: error: 'rng_' was not declared in this scope
```

Reviewed By: yfeldblum

Differential Revision: D4391336

fbshipit-source-id: c27d7a283ad9c52e814e2721a71ba3b3b439db7e