Fix SecurityTest and other tests using TestThriftServerFactory
Summary:
TestThriftServerFactory used a queue length of 2, which is not
enough given the number of threads (1) and pending tasks number (5).

Errors manifested as
```
ERROR: ThreadManager: Failed to enqueue item. Increase maxQueueLen?
```

Test Plan: fbmake runtests

Reviewers: andrewcox, haijunz

Reviewed By: haijunz

Subscribers: alandau, bmatheny, yfeldblum

Differential Revision: https://phabricator.fb.com/D2224351

Signature: t1:2224351:1436307806:313e6396bdd3da07a3f791fdc3ffa49dd65aac0c