Fix Linux CI build
Summary:
D37695718 (https://github.com/facebook/fbthrift/commit/b93c9911f90e3e2f1ec60a37355558e92ca1320e) added a missing openssl dependency to fbthrift manifest. It solved a build issue when running fbcode builder manually per instructions in https://github.com/facebook/fbthrift#building but broke the Linux CI:
```
Extract /tmp/fbcode_builder_getdeps-ZhomeZrunnerZworkZfbthriftZfbthriftZbuildZfbcode_builder/downloads/openssl-openssl-1.1.1l.tar.gz -> /tmp/fbcode_builder_getdeps-ZhomeZrunnerZworkZfbthriftZfbthriftZbuildZfbcode_builder/extracted/openssl-openssl-1.1.1l.tar.gz
Traceback (most recent call last):
  File "build/fbcode_builder/getdeps.py", line 1275, in <module>
    sys.exit(main())
  File "build/fbcode_builder/getdeps.py", line 1258, in main
    return args.func(args)
  File "build/fbcode_builder/getdeps.py", line 109, in run
    self.run_project_cmd(args, loader, manifest)
  File "build/fbcode_builder/getdeps.py", line 611, in run_project_cmd
    loader,
  File "/home/runner/work/fbthrift/fbthrift/build/fbcode_builder/getdeps/manifest.py", line 592, in create_prepare_builders
    builder = self.get_builder_name(ctx)
  File "/home/runner/work/fbthrift/fbthrift/build/fbcode_builder/getdeps/manifest.py", line 457, in get_builder_name
    raise Exception("project %s has no builder for %r" % (self.name, ctx))
Exception: project openssl has no builder for <getdeps.manifest.ManifestContext object at 0x7fef23426860>
```
Log: https://github.com/facebook/fbthrift/runs/7243665517?check_suite_focus=true#step:57:37

This diff fixes the Linux CI by making it use openssl installed in the system. As a nice side effect the CI is now closer to the documented build instructions.

Differential Revision: D37723612

fbshipit-source-id: 22bf0ae0a44ad801c15647b82e4ce8ed5f77ce37