bugfix cpp.minimize_padding with noexcept move c'tor
Summary:
We support automatic reordering of fields to minimize padding using `cpp.minimize_padding` since D9353622 in 2018.

When combined with `cpp.noexcept_move` we have a bug.  We need to generate the move c'tor fields in "layout order" to avoid:
```
error: field 'small' will be initialized after field 'big' [-Werror,-Wreorder]
```

Reviewed By: ot

Differential Revision: D21172001

fbshipit-source-id: 91f6f13b6ffdf7a91d49a32e90279c09b183f037