Temporarily disconnect Any and TypeRegistery from OSS
Summary:
oss windows build are failing due to folly::Poly is not supported windows build.

```
// example error message
D:\a\fbthrift\fbthrift\thrift/lib/cpp2/type/detail/AnyData.h(21): fatal error C1083: Cannot open include file: 'folly/Poly.h': No such file or directory
```

Reviewed By: Alfus

Differential Revision: D36382983

fbshipit-source-id: ab0697f86c0a54bab6bd8edab34749e685b1048e