Fix build failure
Summary:
FieldId is defined as an empty enum. Some compilers would report a warning if we use it in switch-case

```
error: case value not in enumerated type 'apache::thrift::FieldId' (aka 'apache::thrift::type::FieldId') [-Werror,-Wswitch]
[CONTEXT] case FieldId{1}: {
[CONTEXT] ^
```

Reviewed By: thedavekwon

Differential Revision: D52172806

fbshipit-source-id: 362b53c58a3a04220bc988f315e5868d2a30bb62