thrift/lib/cpp2/util/LegacyRequestExpiryGuard.h: add a constructor to accommodate C++20
Summary:
Add an explicit constructor, now required for C++20, see https://en.cppreference.com/w/cpp/language/default_constructor
This avoids the following errors:

  thrift/lib/py/server/CppServerWrapper.cpp:250:46: error: no matching constructor for initialization of 'apache::thrift::LegacyRequestExpiryGuard'

Differential Revision: D32218406

fbshipit-source-id: d6a9cc2d249d58e5081eaea48420051d0b382968