fix `build_fixtures` not working with Python 3
Summary:
In Python 3 `subprocess.Popen.communicate()` returns `bytes`, while both
`sys.stdout.write()` and `sys.stderr.write()` require `str`.  Fix that by
decoding `bytes` to `str` using an appropriate encoding.

Before:
```
$ thrift/compiler/test/build_fixtures buck-out/dev/gen
Building fixture  1/38: basic
...
Building fixture 38/38: types
Traceback (most recent call last):
  File "thrift/compiler/test/build_fixtures", line 109, in <module>
    sys.stdout.write(out)
TypeError: write() argument must be str, not bytes

$
```

After:
```
$ thrift/compiler/test/build_fixtures buck-out/dev/gen
Building fixture  1/38: basic
...
Building fixture 38/38: types

$
```

Reviewed By: eduardo-elizondo

Differential Revision: D5461152

fbshipit-source-id: bcf65e845a7769f5b11bfb5cb9c35d82c570680e