Implement escape sequences for quotes
Summary:
Implement `\"` and `\'` escape sequences in the lexer allowing cases like "a\"b" which would previously result in various errors.

For example

```
const string s = "\"";
```

gave a confusing Thrift error:

```
[ERROR:thrift/test/test.thrift:25] expected header or definition
```

Here `"\"` was lexed as a string literal and stray `"` resulted in an invalid token at the top-level where a start of a definition is expected, thus the error.

The following example:

```
const string s = '\"';
```

would result in a C++ error:

```
test_constants.h:17:48: error: missing terminating '"' character [-Werror,-Winvalid-pp-token]
  static constexpr char const * const s_ = "\\"";
                                               ^
```
because of invalid generated C++ code.

There were also bugs when these escape sequences were emitted in raw strings (this happened in metadata).

This change makes it unnecessary for code generators to deal with these escape sequences themselves fixing all of these issues.

Reviewed By: iahs

Differential Revision: D44354808

fbshipit-source-id: df31f76e938a606c93b2dc5342f899936bcb5573