Fix Rust name conflict if thrift file contains struct called Result
Summary:
Apparently `Result` is a pretty common name for Thrift structs.

Before this diff, the error would be:

```
error[E0107]: wrong number of type arguments: expected 0, found 2
   --> buck-out/dev/gen/.../if-rust-shared.thrift=gen-rust/lib.rs/gen-rust/lib.rs:718:45
    |
718 |         fn from_str(string: &str) -> Result<Self, Self::Err> {
    |                                             ^^^^  ^^^^^^^^^ unexpected type argument
    |                                             |
    |                                             unexpected type argument
```

Reviewed By: Imxset21

Differential Revision: D18319015

fbshipit-source-id: e1f98ba5d9c133805dc9e834d5b4dced48fdaead