fix edencommon build on windows
Summary:
Fix edencommon build on windows, noticed it was breaking the watchman build.

  *  fix boost local build with vs build tools 2022 17.14 update. Without this could not build boost locally. Apply patch as per https://github.com/boostorg/boost/issues/914
  *  in buildopts.py check the 32 bit install location as non-github windows machines like my laptop end up with it installed there
  *  fix the actual problem in edencommon `error C2039: 'wstring': is not a member of 'std'` , which was a missing <string> include

Reviewed By: bigfootjon

Differential Revision: D86630363

fbshipit-source-id: b4993c74cd51d326efb458a6dc461d355f8daeab