Ensure size >=0 while unserializing TBinaryProtocol
Summary:
Trying to deserialize bad messages caused a "ValueError: negative buffersize in recv" error in python rather than a nice Thrift error.

  ERROR:core_services.configerator:Caught non-thrift exception. negative buffersize in recv
  Traceback (most recent call last):
    [...]
    File "thrift/protocol/TBinaryProtocol.py", line 155, in readMessageBegin
    File "thrift/protocol/TBinaryProtocol.py", line 219, in readI32
    File "thrift/transport/TTransport.py", line 75, in readAll
    File "thrift/transport/TTransport.py", line 314, in read
    File "thrift/transport/TTransport.py", line 320, in readFrame
    File "thrift/transport/TTransport.py", line 75, in readAll
    File "thrift/transport/TSocket.py", line 282, in read
  ValueError: negative buffersize in recv

This makes sure we check for the sizes to be >= 0

Reviewed By: serj-de-sudden, yfeldblum

Differential Revision: D4789236

fbshipit-source-id: 6f9fa36a8eb9b8ec021acc379abf80835046a3af