Provide only 1 transport() function per Thrift client
Summary:
Previously, every client trait in a service inheritance chain would contain a separate `.transport()` trait method for accessing the underlying fbthrift transport (e.g. ServiceRouterChannel).

If we have `service DerivedService extends BaseService` then:

```lang=rust
pub trait BaseServiceExt<T>
where
    T: Transport,
{
    ...
    fn transport(&self) -> &T {
        &self.transport
    }
}

pub trait DerivedServiceExt<T>: BaseServiceExt<T>
where
    T: Transport,
{
    ...
    fn transport(&self) -> &T {
        self.parent.transport()
    }
}
```

This causes friction because calls to `.transport()` must be disambiguated with which of these **identical** `transport` methods they want to call.

Various forms of calling `transport`:

```lang=rust
let channel = SRChannelBuilder::from_service_name(fb, "...")
    .unwrap()
    .with_client_params(srclient::ClientParams::new().with_localhost_only(port))
    .build_channel()
    .unwrap();

let client = DerivedServiceImpl::<CompactProtocol<ServiceRouterChannel>, _>::new(channel);

// inherent method
let _ = client.transport();

// statically dispatched trait method
let _ = <BaseServiceExt<_>>::transport(&client);

// dynamically dispatched trait method
let _ = (&client as &dyn DerivedServiceExt<_>).transport();

// dynamically dispatched trait method from supertrait
let _ = (&client as &dyn BaseServiceExt<_>).transport();
let _ = <AsRef<dyn BaseServiceExt<_>>>::as_ref(&client).transport();
```

Previously, calling `.transport()` on `dyn DerivedServiceExt` would be ambiguous because there are 2 such trait methods, and `dyn DerivedServiceExt` implements both traits.

```lang=text,counterexample
error[E0034]: multiple applicable items in scope
   --> path/to/repro.rs:357:52
    |
357 |     let _ = (&client as &dyn DerivedServiceExt<_>).transport();
    |                                                    ^^^^^^^^^ multiple `transport` found
    |
note: candidate #1 is defined in the trait `DerivedServiceExt`
   --> path/to/repro.rs:2416:5
note: candidate #2 is defined in the trait `BaseServiceExt`
   --> path/to/repro.rs:913:5
help: disambiguate the method for candidate #1
    |
357 |     let _ = DerivedServiceExt::transport(&(&client as &dyn DerivedServiceExt<_>));
    |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
help: disambiguate the method for candidate #2
    |
357 |     let _ = BaseServiceExt::transport(&(&client as &dyn DerivedServiceExt<_>));
    |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This diff removes the `transport` trait method of any service that extends another service, leaving every service with exactly one `transport` method among its client trait hierarchy.

Reviewed By: diliop

Differential Revision: D59937771

fbshipit-source-id: af10081d19fa7ce3748c9aadfd9d1a50d43e35a7