Starlark codegen fix
Summary:
## Problem

Generated Starlark code (specifically `record` definition) does not have a valid syntax after D55554386 landed. Currently it's failing with the following error:

```
error: String literals are not allowed in type expressions: `str`
```

`str.type` is a type of `str` and `record` expects a type.

## Solution

Pass types instead of string representation of these types.

Reviewed By: PatrickKan

Differential Revision: D55938672

fbshipit-source-id: 4d747be9d02527322ecd2ed992202d39dc43eecb