Add a missing include
Summary:
Fixes:

```
In file included from xplat/thrift/lib/cpp2/transport/rocket/test/util/TestUtil.cpp:17:
In file included from ./xplat/thrift/lib/cpp2/transport/rocket/test/util/TestUtil.h:34:
In file included from ./xplat/thrift/lib/cpp2/transport/util/ConnectionManager.h:27:
./xplat/thrift/lib/cpp2/transport/util/ConnectionThread.h:30:1: error: unknown type name 'DECLARE_string'
   30 | DECLARE_string(transport);
      | ^
xplat/thrift/lib/cpp2/transport/rocket/test/util/TestUtil.cpp:22:1: error: unknown type name 'DECLARE_int32'
   22 | DECLARE_int32(num_client_connections);
      | ^
xplat/thrift/lib/cpp2/transport/rocket/test/util/TestUtil.cpp:23:1: error: unknown type name 'DECLARE_string'
   23 | DECLARE_string(transport); // ConnectionManager depends on this flag.
      | ^
xplat/thrift/lib/cpp2/transport/rocket/test/util/TestUtil.cpp:33:3: error: use of undeclared identifier 'FLAGS_transport'
   33 |   FLAGS_transport = transport; // client's transport
      |   ^
```

Reviewed By: iahs

Differential Revision: D75095982

fbshipit-source-id: d307040b93d227d064088d7ff73b27212d96ebf8