Mark more reflection functions as deprecated
Summary:
D75560034 marked reflection module functions as deprecated. This causes issues at the callsites (see a build link below)

From the callstack, it is clear that issue occurs when headers are included via `#include`, so we don't even need to call the deprecated function to get this warning.

```bash
In file included from buck-out/v2/gen/fbcode/dsi/logger/multiplex_configs/ThirdPartyMeasurementPlatformMultiplexLoggerConfig/__multiplex_logger__/5ef25bea786cdb69/buck-headers/dsi/logger/multiplex_configs/ThirdPartyMeasurementPlatformMultiplexLoggerConfig/MultiplexLogger.h:11:
In file included from buck-out/v2/gen/fbcode/dsi/logger/configs/ThirdPartyMeasurementPlatformLoggerConfig/__logger__/588906bda9580524/buck-headers/dsi/logger/configs/ThirdPartyMeasurementPlatformLoggerConfig/Logger.h:36:
In file included from buck-out/v2/gen/fbcode/common/thrift/cpp/__isset_utils__/c81735f3cd86e030/buck-headers/common/thrift/cpp/IssetUtils.h:5:
In file included from buck-out/v2/gen/fbcode/thrift/lib/cpp2/reflection/__reflection__/0ee718336d6b81ef/buck-headers/thrift/lib/cpp2/reflection/reflection.h:1302:
buck-out/v2/gen/fbcode/thrift/lib/cpp2/reflection/__reflection__/0ee718336d6b81ef/buck-headers/thrift/lib/cpp2/reflection/internal/reflection-inl-post.h:53:7: error: 'is_reflectable_struct' is deprecated: Deprecated in favor of https://www.internalfb.com/intern/staticdocs/thrift/docs/fb/languages/cpp/reflection and https://github.com/facebook/fbthrift/blob/main/thrift/lib/cpp2/op/Get.h [-Werror,-Wdeprecated-declarations]
   53 |       is_reflectable_struct<T>::value,
      |       ^
buck-out/v2/gen/fbcode/thrift/lib/cpp2/reflection/__reflection__/0ee718336d6b81ef/buck-headers/thrift/lib/cpp2/reflection/internal/reflection-inl-post.h:53:7: note: in instantiation of template type alias 'is_reflectable_struct' requested here
buck-out/v2/gen/fbcode/thrift/lib/cpp2/reflection/__reflection__/0ee718336d6b81ef/buck-headers/thrift/lib/cpp2/reflection/reflection.h:960:31: note: 'is_reflectable_struct' has been explicitly marked deprecated here
  960 | using is_reflectable_struct [[deprecated(
      |                               ^
buck-out/v2/gen/fbcode/thrift/lib/cpp2/reflection/__reflection__/0ee718336d6b81ef/buck-headers/thrift/lib/cpp2/reflection/reflection.h:966:25: error: 'try_reflect_struct' is deprecated: Deprecated in favor of https://www.internalfb.com/intern/staticdocs/thrift/docs/fb/languages/cpp/reflection and https://github.com/facebook/fbthrift/blob/main/thrift/lib/cpp2/op/Get.h [-Werror,-Wdeprecated-declarations]
```

There are two reasons why it is happening

* In `reflection` module, there are non-deprecated struct definitions that depend on deprecated structs.
* in `IssetUtils.h` there is non-deprecated function that calls deprecated code.

Note that this happens only in packages built with `-Werror=deprecated-declarations` enabled. That is quite annoying because it prevents having stricter compiler checks enabled anywhere with Thrift included as a dependency.

The proposed fix is to mark more structs from `reflection` module as deprecated and suppress deprecation warnings inside `IssetUtils.h`.
I tried to upgrade `IssetUtils.h` to use Always-on reflection, but I am not competent enough to do it. If anyone has any pointers how to do that, I am happy to try again.

 https://www.internalfb.com/buck2/6ba66bcb-f679-4355-befb-8dccd03e1e92)

Reviewed By: iahs

Differential Revision: D82744845

fbshipit-source-id: 717ae9d1f52a82ee2cc2006d35c06bec61f39c8f