Add a missing include in cursor-based serializer
Summary:
Add a missing `<variant>` include.

Fixes:
```
CursorBasedSerializer.h(185): error C2143: syntax error: missing ';' before '<'
```

Reviewed By: avalonalex

Differential Revision: D60457192

fbshipit-source-id: 7224e1585129709ee4217be04da2592248bd87e3