Add a checked construction from size_t
Summary:
Previously, `mstch::node` was constructible from `int`, but not from `size_t`:

```lang=text,counterexample
buck-out/v2/gen/fbcode/72ae41e9eca77500/thrift/compiler/generate/__generate__/buck-headers/thrift/compiler/generate/mstch_objects.h:481:12: error: no viable conversion from returned value of type 'std::vector::size_type' (aka 'unsigned long') to function return type 'mstch::node'
    return program_->intern_list().size();
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
buck-out/v2/gen/fbcode/72ae41e9eca77500/thrift/compiler/detail/mustache/__mustache__/buck-headers/thrift/compiler/detail/mustache/mstch.h:134:8: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'std::vector::size_type' (aka 'unsigned long') to 'const apache::thrift::mstch::node &' for 1st argument
struct node : internal::node_base<node> {
       ^
buck-out/v2/gen/fbcode/72ae41e9eca77500/thrift/compiler/detail/mustache/__mustache__/buck-headers/thrift/compiler/detail/mustache/mstch.h:134:8: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'std::vector::size_type' (aka 'unsigned long') to 'apache::thrift::mstch::node &&' for 1st argument
buck-out/v2/gen/fbcode/72ae41e9eca77500/thrift/compiler/detail/mustache/__mustache__/buck-headers/thrift/compiler/detail/mustache/mstch.h:138:18: note: candidate constructor not viable: no known conversion from 'std::vector::size_type' (aka 'unsigned long') to 'std::string_view' (aka 'basic_string_view<char>') for 1st argument
  /* implicit */ node(std::string_view sv) : base(std::string(sv)) {}
                 ^
fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/variant:1399:2: note: candidate template ignored: requirement '18446744073709551615UL < sizeof...(_Types)' was not satisfied [with _Tp = unsigned long, $1 = void, $2 = void]
        variant(_Tp&& __t)
        ^
note: remaining 4 candidates omitted; pass -fshow-overloads=all to show them
```

But nodes whose value is determined by `.size()` of some collection is a common use case, so 2 workarounds are in use:

- a truncating cast from `size_t` to `int`:

https://www.internalfb.com/code/fbsource/[d9ef90475b5bb75d10745d9bf8dfb7f0e28e0e91]/fbcode/thrift/compiler/generate/t_mstch_java_generator.cc?lines=1104-1106

- create a `mstch::node` holding a `std::string`, instead of `int`:

https://www.internalfb.com/code/fbsource/[d9ef90475b5bb75d10745d9bf8dfb7f0e28e0e91]/fbcode/thrift/compiler/generate/t_mstch_cpp2_generator.cc?lines=1204

This diff adds a new `mstch::node` constructor taking `size_t` and producing a node containing `int`, or an exception on overflow.

I don't expect that we will ever observe this exception in practice, but if we do, it might be reasonable to adjust this constructor to use `std::to_string`, either unconditionally or only in the case of `int` overflow.

Reviewed By: iahs

Differential Revision: D57946616

fbshipit-source-id: c4a1ff1d993f92472ac555a4d6468fa5fff6f335