Add CompressionAlgorithmSelector.cpp to CMakeLists.txt
Summary:
Ran into the following error while trying to build OSS FBOSS: P1669423307

```
/usr/bin/ld: /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftcpp2.a(RpcMetadataUtil.cpp.o): in function `apache::thrift::detail::makeRequestRpcMetadata(apache::thrift::RpcOptions const&, apache::thrift::RpcKind, apache::thrift::ManagedStringView&&, std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >, std::variant<apache::thrift::InteractionCreate, long, std::monostate>, bool, long, apache::thrift::transport::THeader&)':
RpcMetadataUtil.cpp:(.text+0xef5): undefined reference to `apache::thrift::rocket::CompressionAlgorithmSelector::fromCodecConfig(apache::thrift::CodecConfig const&)'
```

Looks like a new source file is missing from OSS, was recently added in D61996811

Reviewed By: cevans87

Differential Revision: D65175075

fbshipit-source-id: ed82e3ab4fcd46e45cb80c81d7d59f4839e376c6