Add netty to common runtime deps
Summary:
I need to make all `binary` writes consistent - for Whisker unification work downstream.

To do that - I need to add a direct `netty` dependency to Thrift libs.

Without it - the compilation fails:
```
$ buck build fbcode//thrift/lib/java/...
....
/re_tmp/tmptgwx5gs2/extracted_srcs/data-type/org/apache/thrift/HeadersPayloadContent.java:174: error: cannot access ByteBuf
                org.apache.thrift.protocol.TProtocolUtil.writeBinary(oprot, _iter2);
                                                        ^
  class file for io.netty.buffer.ByteBuf not found
```

Reviewed By: j-bahr, praihan

Differential Revision: D98828759

fbshipit-source-id: d801a951a5a5eb6a7110663a89e36bbb99b9a9e1