Do not shadow variable names.
Summary:
Clang under restrictive compilation flags will fail due to:
```
thrift/lib/cpp2/async/ReplyInfo.h:135:37: error: declaration shadows a local variable [-Werror,-Wshadow-uncaptured-local]
    std::visit([&evb = evb_](auto&& info) { info(evb); }, info);
                                    ^
thrift/lib/cpp2/async/ReplyInfo.h:135:37: error: declaration shadows a local variable [-Werror,-Wshadow-uncaptured-local]
    std::visit([&evb = evb_](auto&& info) { info(evb); }, info);
```

Let us ensure that we don't shadow variable names.

Reviewed By: boyuni

Differential Revision: D27326728

fbshipit-source-id: 64a5182f054800f4bc8c17cfd0b4afd6fc453549