Fix thrift OSS build failures
Summary:
- D88914078 introduced RocketRequestHandler.cpp but didn't add it to fbthrift cmake which broke our FBOSS OSS:

https://www.internalfb.com/ci/error_insights/cluster/1219925483102620
```
RefactoredThriftRocketServerHandler.cpp:(.text+0xe37): undefined reference to `apache::thrift::rocket::RocketRequestHandler::coalesceProcessorWithLegacyEventHandlers()'
```

- D92071882 started using dynamic:path in dynamic_value but didn't add such dependency in the thrift cmake file
```
in function `std::optional<apache::thrift::dynamic::DynamicRef> apache::thrift::dynamic::DynamicConstRef::traverseImpl<apache::thrift::dynamic::DynamicRef>(apache::thrift::dynamic::DynamicRef, apache::thrift::dynamic::Path const&)':

DynamicValue.cpp:(.text._ZN6apache6thrift7dynamic15DynamicConstRef12traverseImplINS1_10DynamicRefEEESt8optionalIT_ES6_RKNS1_4PathE[_ZN6apache6thrift7dynamic15DynamicConstRef12traverseImplINS1_10DynamicRefEEESt8optionalIT_ES6_RKNS1_4PathE]+0xe6): undefined reference to `apache::thrift::dynamic::detail::typeDisplayName[abi:cxx11](apache::thrift::type_system::TypeRef const&)'
```

- Besides when I am fixing the above two issues, I also noticed the following issue. Looks like fmt::fmt couldn't format the enum class FieldId correctly with current implementation
```
/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fbthrift.git/thrift/lib/cpp2/dynamic/Path.cpp:179:24:   required from here
/var/FBOSS/tmp_bld_dir/installed/fmt-F0GUNLEpOf0DWem-8v1_jJNSY0OJfSn5BLYDZxh85Nc/include/fmt/base.h:2310:45: error: ‘fmt::v12::detail::type_is_unformattable_for<apache::thrift::type::FieldId, char> _’ has incomplete type
 2310 |     type_is_unformattable_for<T, char_type> _;
      |                                             ^
```

Differential Revision: D92776512

fbshipit-source-id: cf8058d54eb2bc7b9bccab234d5def6575f57e34