thrift: get rid of a use of sprintf
Summary:
Annoyed to be constantly seeing a lint "error" for this sprintf
use on my interminable https://phabricator.fb.com/D2190362,
I've replaced it with a use of snprintf+assert.

Depends on D2192752

Test Plan:
  fbconfig -r thrift && fbmake dev && fbmake runtests_dev

Currently the above fails to compile:

  thrift/test/Cpp2OpsTest.cpp:45:21: error: 'thrift::test::cpp2ops::cpp2::Cpp2OpsCompat_constants_codemod' has not been declared

but Marcelo has a fix for that (D2192752).
I will rerun, once I rebase past his fix.

Reviewers: andrewcox, tjackson, alandau, philipp, marcelo, sugak, markisaa, davejwatson

Reviewed By: davejwatson

Subscribers: alandau, yfeldblum

Differential Revision: https://phabricator.fb.com/D2194762

Signature: t1:2194762:1435334090:29b5080a8b8c34a8709c40d8969af90068fd7b44