Fixing broken fbthrift OSS linkage
Summary:
It looks like D7905636 broke linking against libasync in fbthrift:

[ 84%] Linking CXX executable wedge_agent
../external.install/lib/libthriftcpp2.a(ThriftServer.cpp.o): In function
`apache::thrift::ThriftServer::setup()':
ThriftServer.cpp:(.text+0x249d): undefined reference to
`apache::thrift::server::observerFactory_'
ThriftServer.cpp:(.text+0x24bb): undefined reference to
`apache::thrift::server::observerFactory_'
collect2: error: ld returned 1 exit status
CMakeFiles/wedge_agent.dir/build.make:285: recipe for target 'wedge_agent'
failed

This patch re-adds the moved file to CMakeLists.txt

Reviewed By: yfeldblum, boryas

Differential Revision: D7975324

fbshipit-source-id: 4fe16a70e19ac6abd55890cfe0bd57775130d69a