Fix TSimpleJSONProtocol failing under Python 3, TJSONProtocol containing invalid names
Summary: Without this change Python 3 complains about not being able to compare b'' from JSON_CHAR_TABLE with a number.

Test Plan:
The following works under Python 3 now:

```
proto_factory = TSimpleJSONProtocolFactory()
transport = TMemoryBuffer()
thrift_obj.write(proto_factory.getProtocol(transport))
thrift_obj_bytes = transport.getvalue()
```

instead of raising:

```
Traceback (most recent call last):
...
  File "/proc/self/fd/4/thrift/protocol/TSimpleJSONProtocol.py", line 699, in writeString
    self.writeJSONString(outStr)
  File "/proc/self/fd/4/thrift/protocol/TSimpleJSONProtocol.py", line 378, in writeJSONString
    self.writeJSONChar(ch)
  File "/proc/self/fd/4/thrift/protocol/TSimpleJSONProtocol.py", line 368, in writeJSONChar
    elif outCh > 1:
TypeError: unorderable types: bytes() > int()
```

Reviewers: anarayanan, fried, haijunz, jhitchcock

Reviewed By: jhitchcock

Subscribers: alandau, bmatheny, yfeldblum

Differential Revision: https://phabricator.fb.com/D2229247

Signature: t1:2229247:1436405026:eeb556da89ccfac0fe3159c860d88d7627d81a4e