Fix cmake rebuild of generators
Summary:
If you try rebuilding thrift via cmake after `thrift/compiler/generate/templates.cc` has been generated you'll get the following error:

```
/usr/bin/ld: ../../lib/libcompiler_generators.a(templates.cc.o):(.rodata+0x0): multiple definition of `apache::thrift::compiler::templates_size'; ../../lib/libcompiler_generators.a(templates.cc.o):(.rodata+0x0): first defined here
```

because `templates.cc.o` is added twice to the static library, once as a source and once as an object file. Fix it and simplify CMake config.

Reviewed By: Mizuchi

Differential Revision: D27870030

fbshipit-source-id: ab7f460394a3f4778100467b0f133c580c51bf12