Change py3 union field accessor to throw AttributeError instead of TypeError
Summary:
This was brought up in a complaint in the user group, but field accessors are only supposed to throw AttributeError, weird behaviour arises when they throw TypeError, for example
```
In [4]: getattr(rule_event, "xxxx", 1)
Out[4]: 1

In [5]: getattr(rule_event, "dynamic", 1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/fbsource/fbcode/buck-out/dev/gen/whatsapp/data_infra/telemetry/forwarding/compile#link-tree/whatsapp/data_infra/telemetry/forwarding/compiler.py in <module>
----> 1 getattr(rule_event, "dynamic", 1)

whatsapp.data_infra.telemetry.forwarding/forward_schema/types.pyx in whatsapp.data_infra.telemetry.forwarding.forward_schema.types.constant_t.dynamic.__get__()

TypeError: Union contains a value of type named_bundle, not dynamic
```
getattr raises a TypeError instead of giving a default value because it doesn't expect a TypeError to get thrown when accessing `rule_event.dynamic`.

Reviewed By: nanshu

Differential Revision: D32445213

fbshipit-source-id: fb12fc468a6b06a819721834e498a1857aa56b4d