fix some oss build for rocket
Summary:
Another build failure is reported:

```
/opt/app/installed/fbthrift/lib/librocketupgrade.a(RequestsRegistry.cpp.o): In function `apache::thrift::detail::PluggableFunction<unsigned long>::operator()()':

/opt/app/repos/github.com-facebook-fbthrift.git/thrift/lib/cpp2/PluggableFunction.h:82: undefined reference to `apache::thrift::detail::getPluggableFunction(apache::thrift::detail::PluggableFunctionMetadata*)'
/opt/app/installed/fbthrift/lib/librocketupgrade.a(RequestsRegistry.cpp.o): In function `apache::thrift::detail::PluggableFunction<unsigned long>::PluggableFunction(folly::Range<char const*>, unsigned long (*)())':
/opt/app/repos/github.com-facebook-fbthrift.git/thrift/lib/cpp2/PluggableFunction.h:74: undefined reference to `apache::thrift::detail::registerPluggableFunction(folly::Range<char const*>, std::type_index, long)'
collect2: error: ld returned 1 exit status
[1443/1444] Linking CXX executable sai_test-sai_impl-1.7.0
```

Instead of adding PluggableFunction.cpp into rocketupgrade, it is better to let rocketupgrade link with thriftcpp2 instead? Otherwise source files will gradually leak into rocketupgrade that seems not to be ideal.

Reviewed By: vitaut

Differential Revision: D27025233

fbshipit-source-id: 5074357dd9aac562320ff1fec8ada2038b37fb26