remove buggy reversed impl
Summary:
`__reversed__` implementation in thrift py3 EnumMeta is buggy and always raises:
```
TypeError: '_cython_3_0_8.generator' object is not reversible
```

Looking ahead to thrift-python, `EnumMeta.__iter__` uses dict value iter, which is also not iterable, so thrift-python doesn't implement `__reverse__` either. Now both implementations raise `KeyError` with `reversed` usage.

Reviewed By: yoney

Differential Revision: D61622339

fbshipit-source-id: 6affe9488aae3d1e31acbf6f8df234e27152168f