fix unsigned and signed comparison
Summary:
I was building `//crypto/cat/cpp/tests/examples:corp_e2e_manual_test` on Windows and build failed because of this.
`refCount` is `size_t` and it's being compared with `int`. Probably I was building with stricter flags than needed but this fix looks harmless to me.

Full error I had:
```
buck-out/dev/cells/fbsource/gen/third-party/glog/glogWindows#header-mode-symlink-tree-only,headers\glog/logging.h:703:32: error: comparison of integers of different signs: 'const unsigned long long' and 'const int' [-Werror,-Wsign-compare]
DEFINE_CHECK_OP_IMPL(Check_GT, > )
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
buck-out/dev/cells/fbsource/gen/third-party/glog/glogWindows#header-mode-symlink-tree-only,headers\glog/logging.h:687:32: note: expanded from macro 'DEFINE_CHECK_OP_IMPL'
    if (GOOGLE_PREDICT_TRUE(v1 op v2)) return NULL; \
                            ~~ ^  ~~
buck-out/dev/cells/fbsource/gen/third-party/glog/glogWindows#header-mode-symlink-tree-only,headers\glog/logging.h:141:32: note: expanded from macro 'GOOGLE_PREDICT_TRUE'
#define GOOGLE_PREDICT_TRUE(x) x
                               ^
buck-out/dev/gen/thrift/lib/cpp2/async/interaction#header-mode-symlink-tree-only,headers\thrift/lib/cpp2/async/Interaction.h:93:5: note: in instantiation of function template specialization 'google::Check_GTImpl<unsigned long long, int>' requested here
    DCHECK_GT(refCount_, 0);
    ^
buck-out/dev/cells/fbsource/gen/third-party/glog/glogWindows#header-mode-symlink-tree-only,headers\glog/logging.h:980:31: note: expanded from macro 'DCHECK_GT'
#define DCHECK_GT(val1, val2) CHECK_GT(val1, val2)
                              ^
buck-out/dev/cells/fbsource/gen/third-party/glog/glogWindows#header-mode-symlink-tree-only,headers\glog/logging.h:774:30: note: expanded from macro 'CHECK_GT'
#define CHECK_GT(val1, val2) CHECK_OP(_GT, > , val1, val2)
                             ^
buck-out/dev/cells/fbsource/gen/third-party/glog/glogWindows#header-mode-symlink-tree-only,headers\glog/logging.h:745:3: note: expanded from macro 'CHECK_OP'
  CHECK_OP_LOG(name, op, val1, val2, google::LogMessageFatal)
  ^
buck-out/dev/cells/fbsource/gen/third-party/glog/glogWindows#header-mode-symlink-tree-only,headers\glog/logging.h:725:18: note: expanded from macro 'CHECK_OP_LOG'
         google::Check##name##Impl(                      \
                 ^
<scratch space>:14:1: note: expanded from here
Check_GTImpl
^
thrift\lib\cpp2\async\AsyncProcessor.cpp:428:18: note: in instantiation of function template specialization 'apache::thrift::Tile::__fbthrift_releaseRef<apache::thrift::Cpp2ConnContext>' requested here
    interaction->__fbthrift_releaseRef(
                 ^
1 error generated.
    When running <c++ preprocess_and_compile>.
    When building rule //thrift/lib/cpp2:async_processor#compile-AsyncProcessor.cpp.obj9c3cd9ff,windows-x86_64.
```

Reviewed By: Mizuchi, iahs

Differential Revision: D23867300

fbshipit-source-id: 1488387140fc702979a6ec5aaf9fdbdb7d87e24b