fix imports for perf load handler
Summary:
The server won't start due to wrong imports
  ModuleNotFoundError: No module named 'thrift.perf.load_services'

Reviewed By: yfeldblum

Differential Revision: D8530990

fbshipit-source-id: 3565e7993175b44eee300ec27032a8bc59539fca