Improve module reflection compiler error messages
Summary:
This bundles all the reflection arguments into a traits class, so that error messages resemble this:
```
thrift/test/SerializationRoundTripTest.cpp:89:56: error: no member named 'foobar' in 'apache::thrift::reflected_module<apache::thrift::test::testset::__fbthrift_refl::testset_module_traits>'
  reflect_module<test::testset::testset_tags::module>::foobar;
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
1 error generated.
```

Reviewed By: yfeldblum, vitaut

Differential Revision: D25263731

fbshipit-source-id: 1a0378f521633497d4192afb29e2ad3a62f6d2c2