Unbreak Frozen
Summary:
since D1163100 was pushed my project using Frozen fails to compile with:

```
from syseng/bind10/hook_lib/Cache.cpp:4:
./thrift/lib/cpp/Frozen.h:893:16: error: 'unordered_map' is not a member of 'std'
./thrift/lib/cpp/Frozen.h:893:16: error: 'unordered_map' is not a member of 'std'
./thrift/lib/cpp/Frozen.h:893:39: error: template argument 1 is invalid
```

This is probably because you forgot to `#include <unordered_map>`

Test Plan: compiled my project and it works

Reviewed By: tjackson@fb.com

FB internal diff: D1218866

Blame Revision: D1163100