Add ServiceInterceptorQualifiedName.cpp to listfile
This was added in D73136906 but is missing from CMakeLists.txt.

Spotted via https://github.com/facebook/mcrouter/pull/463:

```
/usr/bin/ld: /home/runner/work/mcrouter/mcrouter/mcrouter-install/install/lib/libthriftcpp2.a(ThriftServer.cpp.o): in function `apache::thrift::ThriftServer::processModulesSpecification(apache::thrift::ThriftServer::ModulesSpecification&&)::ServiceInterceptorsCollector::addModule(apache::thrift::ThriftServer::ModulesSpecification::Info const&)':
ThriftServer.cpp:(.text+0x1d1c3): undefined reference to `apache::thrift::ServiceInterceptorQualifiedName::get() const'
```