Fix missing `#include <fstream>`
Without this, the build fails with

    error: implicit instantiation of undefined template 'std::basic_ifstream<char>'

Seen while building for Homebrew at Homebrew/homebrew-core#108112.

See also https://github.com/Homebrew/homebrew-core/runs/7851989695?check_suite_focus=true#step:6:358.