Regression unit-test for recent crash in THttpParser
Summary:
[Thrift] Regression unit-test for recent crash in `THttpParser`.

Filtered crash report, as reproduced by this unit-test, from reverting {D4567032} (https://github.com/facebook/fbthrift/commit/9076ff6fe67e99eea5c4bee2df4d79e11b2bf46d):

    Note: Google Test filter = THttpClientParserTest.read_encapsulated_status_line
    [==========] Running 1 test from 1 test case.
    [----------] Global test environment set-up.
    [----------] 1 test from THttpClientParserTest
    [ RUN      ] THttpClientParserTest.read_encapsulated_status_line
    ASAN:DEADLYSIGNAL
    =================================================================
    ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000
    The signal is caused by a READ memory access.
    Hint: address points to the zero page.
         #1 <binary>                                        strlen
         #2 folly/portability/Constexpr.h:102               unsigned long folly::constexpr_strlen<...>(char const*)
         #3 folly/Range.h:212                               folly::Range<...>::Range<...>(char const*)
         #4 thrift/lib/cpp/util/THttpParser.cpp:208         apache::thrift::util::THttpParser::parseHeader()
         #5 thrift/lib/cpp/util/THttpParser.cpp:87          apache::thrift::util::THttpParser::readDataAvailable(unsigned long)
         #6 thrift/lib/cpp/util/test/THttpParserTest.cpp:20 (anonymous namespace)::write(apache::thrift::util::THttpParser&, folly::Range<...>)
         #7 thrift/lib/cpp/util/test/THttpParserTest.cpp:28 THttpClientParserTest_read_encapsulated_status_line_Test::TestBody()

    AddressSanitizer can not provide additional info.
    SUMMARY: AddressSanitizer: SEGV in __GI_strlen
    ABORTING

After reading a complete status line with terminal CRLF, the parser attempts to read the next header line. Since the parser does not see a CRLF from the beginning of the header line yet, it gets a nullptr from `readLine`. Constructing a `StringPiece` from a `nullptr` is a segfault.

Reviewed By: andrewjcg

Differential Revision: D4582453

fbshipit-source-id: 82a21ed6e23083f903e8a2fbf93be01ad149c4ee