Fix compilation error in thrifty.yy
Work around for error:
```
parse/thrifty.yy:65:13: error: ‘struct apache::thrift::compiler::yy::parser::symbol_type’ has no member named ‘token’
```

Introduced in https://github.com/facebook/fbthrift/commit/0ed89d8d06b546c89c60b0dceab0ac36b73f9515