Fix terse_write_test
Summary:
Fixes a bunch of warnings turned errors:

```
$ buck build fbcode//thrift/test/terse_write:terse_write_test
...
fbcode/thrift/test/terse_write/TerseWriteTest.cpp:219:24: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  219 |   Serializer::template deserialize(objs, objd);
      |                        ^
```

Remove unused includes.

Reviewed By: hchokshi

Differential Revision: D79130926

fbshipit-source-id: fc0f775072e17c0a09afa52eb8872a1e50cb98f9