Fix Java conformance build in xplat
Summary:
Fix remaining build failures in `xplat/thrift/conformance/java`:

```
$ buck build fbsource//xplat/thrift/conformance/java/...
...
xplat/thrift/conformance/java/src/main/java/com/meta/thrift/conformance/data/server/ConformanceServiceImpl.java:65: error: method does not override or implement a method from a supertype
  Override
  ^
xplat/thrift/conformance/java/src/main/java/com/meta/thrift/conformance/data/server/ConformanceServiceImpl.java:76: error: method does not override or implement a method from a supertype
  Override
  ^
xplat/thrift/conformance/java/src/main/java/com/meta/thrift/conformance/rpc/client/RpcClientConformanceHandler.java:101: warning: non-varargs call of varargs method with inexact argument type for last parameter;
      Method getter = ClientInstruction.class.getMethod("get" + name, null);
                                                                      ^
  cast to java.lang.Class<?> for a varargs call
  cast to java.lang.Class<?>[] for a non-varargs call and to suppress this warning
xplat/thrift/conformance/java/src/main/java/com/meta/thrift/conformance/rpc/client/RpcClientConformanceHandler.java:186: error: cannot access org.apache.thrift.conformance.RpcOptions
        .requestResponseTimeout(instruction.getRequest(), rpcOptions)
        ^
...
Error running analysis for `fbsource//xplat/thrift/conformance/java:rpc-server_duplicate_finder (cfg:dev-linux-x86_64-fbcode-platform010-clang19-asan-ubsan-dev#36363614a3f9e467)`

Caused by:
    0: Error in configured node dependency, dependency chain follows (-> indicates depends on, ^ indicates same configuration as previous):
              fbsource//xplat/thrift/conformance/java:rpc-server_duplicate_finder (cfg:dev-linux-x86_64-fbcode-platform010-clang19-asan-ubsan-dev#36363614a3f9e467)
           -> fbsource//xplat/thrift/conformance/java:__unstamped-rpc-server (^)
           -> fbsource//xplat/thrift/conformance/java:rpc-server-gk-definition-lib-java11 (^)
           -> fbsource//xplat/thrift/conformance/java:rpc-server-gk-definition-gen (^)
           -> fbsource//xplat/thrift/conformance/java:rpc-server-gk-list (^)
           -> fbsource//xplat/thrift/conformance/java:conformance-lib-java11 (^)

    1: looking up unconfigured target node `fbsource//xplat/thrift/conformance/java:conformance-lib-java11`
    2: Unknown target `conformance-lib-java11` from package `fbsource//xplat/thrift/conformance/java`.
       Did you mean one of the 31 targets in fbsource//xplat/thrift/conformance/java:BUCK?
       Maybe you meant one of these similar targets?
         fbsource//xplat/thrift/conformance/java:conformance-lib
```

Reviewed By: yoney

Differential Revision: D77876842

fbshipit-source-id: ea994f65f594fc15e794152036d3cbb7241fdb5f