fix unused result error
Summary:
I'm having error building Thrift server on Windows with `mode/opt`. It adds `-DNDEBUG` which causes this line to fail:
```
thrift\lib\cpp2\server\ThriftServer.cpp:221:18: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
  DCHECK_NOTNULL(getProcessorFactory().get());
buck-out/cells/fbsource/gen/third-party/glog/glogWindows#header-mode-symlink-tree-only,headers\glog/logging.h:1046:30: note: expanded from macro 'DCHECK_NOTNULL'
#define DCHECK_NOTNULL(val) (val)
```

Glog comment says to do this:
```
// You may see warnings in release mode if you don't use the return
// value of DCHECK_NOTNULL. Please just use DCHECK for such cases.
```

Reviewed By: xavierd

Differential Revision: D24997076

fbshipit-source-id: d3750ba9612477f710c91d3744a95300ed7da36b