add missing include
Summary:
The "loom" target in fbandroid (`buck build loom`) is breaking on local builds (as
opposed to building on the devserver) with the following error:

```
thrift/compiler/parse/parsing_driver.h:307:35: error: implicit instantiation of undefined template 'std::__1::array<char, 1024>'
```

Reviewed By: yfeldblum

Differential Revision: D9066271

fbshipit-source-id: 448ebf69b42337a2889715e4a3dd681e16658a9d