Mutable structs and unions: add field information to error message on field set
Summary:
Example:

```
Traceback (most recent call last):
  File "thrift.python/mutable_types.pyx", line 232, in thrift.python.mutable_types.MutableStruct._fbthrift_set_field_value
  File "thrift.python/types.pyx", line 165, in thrift.python.types.IntegerTypeInfo.to_internal_data
TypeError: value This is not an integer is not a <class 'int'>, is actually of type <class 'str'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/users/aristidis/fbsource/buck-out/v2/gen/fbcode/d6c672a313a4d8b7/thrift/test/thrift-python/__struct_test__/struct_test#link-tree/thrift/test/thrift-python/struct_test.py", line 630, in test_create_and_assign_for_i32
    s.unqualified_i32 = "This is not an integer"
  File "thrift.python/mutable_types.pyx", line 100, in thrift.python.mutable_types._MutableStructField.__set__
  File "thrift.python/mutable_types.pyx", line 235, in thrift.python.mutable_types.MutableStruct._fbthrift_set_field_value
TypeError: <class 'thrift.test.thrift_python.struct_test.thrift_mutable_types.TestStructAllThriftPrimitiveTypes'>: error setting Thrift struct field 'unqualified_i32': value This is not an integer is not a <class 'int'>, is actually of type <class 'str'>
```

Reviewed By: Filip-F

Differential Revision: D60676939

fbshipit-source-id: 65b9d688c758bb03c962a2f8fc17e4a3524c52ef