Fix ThriftTypeInfo.h build on Mac
Summary:
Apple Clang generates the following error when compiling this file on Mac:
```
thrift/conformance/cpp2/ThriftTypeInfo.h:72:7: error: address of function 'struct_private_access::__fbthrift_cpp2_gen_has_thrift_uri<facebook::cathode::modules::DynamicModuleConfig>' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
      struct_private_access::__fbthrift_cpp2_gen_has_thrift_uri<T>,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
thrift/conformance/cpp2/AnyRegistry.h:259:32: note: in instantiation of function template specialization 'apache::thrift::conformance::getGeneratedThriftTypeInfo<facebook::cathode::modules::DynamicModuleConfig>' requested here
  const ThriftTypeInfo& type = getGeneratedThriftTypeInfo<Struct>();
                               ^
buck-out/dev/gen/03598924/cathode/modules/dynamic/if/dynamic_module-cpp2-dynamic_module.thrift/gen-cpp2/dynamic_module_types.cpp:21:42: note: in instantiation of function template specialization 'apache::thrift::conformance::detail::registerGeneratedStruct<facebook::cathode::modules::DynamicModuleConfig, apache::thrift::conformance::StandardProtocol::SimpleJson, apache::thrift::conformance::StandardProtocol::Compact, apache::thrift::conformance::StandardProtocol::Binary>' requested here
    apache::thrift::conformance::detail::registerGeneratedStruct<
                                         ^
thrift/conformance/cpp2/ThriftTypeInfo.h:72:7: note: prefix with the address-of operator to silence this warning
      struct_private_access::__fbthrift_cpp2_gen_has_thrift_uri<T>,
      ^
      &
```

This causes a build failure higher up in the stack

Reviewed By: thedavekwon

Differential Revision: D33888193

fbshipit-source-id: aa89effd283dee5a8a7d1e616757dbac4906acda