Fix FrozenTest
Summary:
Fix errors of the form
```
thrift/lib/cpp2/test/FrozenTest.cpp:377:20: error: no matching constructor for initialization
 of 'map<std::string, int>' (aka 'map<basic_string<char>, int>')
  map<string, int> tmap{
                   ^   ~
```
in FrozenTest.

In general u8 should be avoided at least because of portability issues and incompatibility with system APIs.

Reviewed By: thedavekwon

Differential Revision: D35651882

fbshipit-source-id: 3b9d7fe212c475929fe80f32474441b635cd4591