Fix opt-gcc build in tests
Summary:
Fix opt-gcc build in `CompactProtocolTest` and `BinaryProtocolTest`:
```
thrift/lib/cpp2/protocol/test/CompactProtocolTest.cpp:24:19: error: missing binary operator before token "("
   24 | #if !__has_feature(undefined_behavior_sanitizer)
      |                   ^
```
Apart from fixing the build this approach is arguably better because it exercises the validation path in all build configs even though UBSAN is locally disabled.

Differential Revision: D29764691

fbshipit-source-id: 4ceefc75e3bed827aa8f4de754d18bdb52479dfa