Fix thrift randomizer for specific structs
Summary:
Sometimes the fields_to_randomize would be empty for StructRandomizer this caused an exception when trying to run random.choice().

The error would be something like:

```
  File "thrift/util/randomizer.py", line 174, in generate
  File "thrift/util/randomizer.py", line 814, in _randomize
  File ".../random.py", line 261, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```

This will fix the exception so we correctly return none rather than throwing an exception.

Reviewed By: yfeldblum

Differential Revision: D15926165

fbshipit-source-id: c64e4212ad5687cd5323ec4024c9ebcce637b511