support backward compatible deserialization of NaN and Infinity values in simplejson_protocol
Summary:
## Problem
Without digging too much into practical applications for our project, it seems that not every round-trip succeeds on the deserializer's side. And it will be easier to demonstrate that behaviour with the example below:

```
/// .thrift file

struct DiagnosticSensorInfo {
  1: optional string name;
  2: optional double reading;
}

/// .rs file

#[cfg(test)]
mod test {
    #[test]
    fn test_f64_nan() {
        let reading: f64 = f64::NAN;
        println!("READING: {:?}", reading);

        let bytes: [u8; 8] = reading.to_le_bytes();
        println!("BYTES: {:?}", bytes);

        let info = DiagnosticSensorInfo {
            reading: Some(reading),
            ..Default::default()
        };
        let serialized = fbthrift::simplejson_protocol::serialize(info);
        println!("SERIALIZED: {:?}", serialized);

        let deserialized: DiagnosticSensorInfo =
            fbthrift::simplejson_protocol::deserialize(&serialized).unwrap();
        println!("DESERIALIZED: {:?}", deserialized);
    }
}
```

Similar to several of my colleagues, I anticipate that this code will perform at its best and not panic. However, the final test result doesn't meet expectations and reveals two essential facts:
- `f64::NAN` is serialized as "2.696539702293474e308" string, which is greater than `f64::MAX` (1.7976931348623157e308)
- "2.696539702293474e308" string is considered invalid number by deserializer
And can be seen in output below:
```
READING: NaN
BYTES: [0, 0, 0, 0, 0, 0, 248, 127]
SERIALIZED: b"{\"reading\":2.696539702293474e308}"
thread 'laser::test::test_f64_nan' panicked at :
called `Result::unwrap()` on an `Err` value: Invalid number
```

## What now?

Most importantly, this change aims to fix breaking deserialization issues while maintaining compatibility with other implementations, including the referenced C++ implementation and those in Rust and other languages.

## What next?

After this change has been rolled out to all internal users, I plan to introduce another breaking change related to serialization implementation. This update will modify the string representation of NaN and Infinity values to align with the reference C++ implementation. Rest assured that all necessary precautions will be taken and overseen by the Rust group.

Reviewed By: guswynn

Differential Revision: D69896868

fbshipit-source-id: acbeb4bfaa2d9bfc0b1445a72bef49b678d6142a