Add ServiceInterceptorQualifiedName.cpp to listfile (#648)
Summary:
This was added in D73136906 but is missing from CMakeLists.txt.

Spotted via https://github.com/facebook/mcrouter/pull/463:

```
/usr/bin/ld: /home/runner/work/mcrouter/mcrouter/mcrouter-install/install/lib/libthriftcpp2.a(ThriftServer.cpp.o): in function `apache::thrift::ThriftServer::processModulesSpecification(apache::thrift::ThriftServer::ModulesSpecification&&)::ServiceInterceptorsCollector::addModule(apache::thrift::ThriftServer::ModulesSpecification::Info const&)':
ThriftServer.cpp:(.text+0x1d1c3): undefined reference to `apache::thrift::ServiceInterceptorQualifiedName::get() const'
```

Pull Request resolved: https://github.com/facebook/fbthrift/pull/648

Reviewed By: vitaut

Differential Revision: D73378222

Pulled By: iahs

fbshipit-source-id: 676caa94c1566dc1b6275fc2cb4ba3043789cd42