Fix "must be initialized by a constant expression"
Summary:
When building with `-march=haswell` with the Xcode toolchain that enables `__BMI2__` which exercises this code, resulting in errors:
```
xplat/thrift/lib/cpp/util/VarintUtils-inl.h:178:53: note: non-literal type '(lambda at xplat/thrift/lib/cpp/util/VarintUtils-inl.h:178:53)' cannot be used in a constant expression
  static constexpr std::array<uint8_t, 64> kShift = []() {
                                                    ^
xplat/thrift/lib/cpp/util/VarintUtils-inl.h:186:44: error: constexpr variable 'kSize' must be initialized by a constant expression
  static constexpr std::array<uint8_t, 64> kSize = []() {
                                          ^       ~~~~~~
```
so use `const` instead of `constexpr`

Reviewed By: luciang

Differential Revision: D35254120

fbshipit-source-id: d9540d6719146c9ec2a519194c736cb121726c13