switch from list-initialization to make_tuple in struct metadata codegen.
Summary:
Fixing build errors on Android platform like:
```
error: chosen constructor is explicit in copy-initialization
    {1, "topic", false, std::make_unique<Primitive>(ThriftPrimitiveType::STRING)},
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/android_ndk/r17fb2/sources/cxx-stl/gnu-libstdc++/4.9/include/tuple:406:19: note: explicit constructor declared here
        constexpr tuple(_UElements&&... __elements)
```
since this is not compatible with libstdc++ 4.9 which is used by android NDK.

Differential Revision: D20039904

fbshipit-source-id: 1b3db0214819ce616cd1a78cc8d4081f23da7a69