Extend thrift-py3 to compile and run all unittests
Compiles all thriftpy3 unit tests; all of them run, through with some
failures.

After significant difficulty both co-ordinating with and build
performance issues with a separate setuptools build step for Cython,
have move thriftpy3 to CMakei-only build.

This version has the following limitations:

  * No dependency detection in Cython sources
  * No installation rules for thriftpy3 libraries

Each of these will improved in follow-up diffs.

* Create thriftcpp2_shared.so

Number of the symbols used from within thrift and folly need to be
singletons. In the initial prototype, had been statically linking
everything, which works until two thrift modules need to be loaded
simultaneously, a significant example of this is running unit tests.

All code for the shared library needs to be compiled with position
independent code -fPIC, so cpp and cpp2 static libs are replicated
with _pic variants.

Other notes:

* Automatically create __init__.py when generating thrift-py3 library

Builds thrift/lib/py3 (without tests) using only CMake

* To Work around name conflict with folly.executor, __init__.pyx is used
  for folly.iobuf. This can be resolved once folly.iobuf is moved to
  thrift, in a future diff.

Test Plan:

  $ mkdir -p fbthrift/_build
  $ cd fbthrift/_build
  $ export PYTHONPATH=$(pwd)/thrift/lib/py3/cybld/
  $ cmake -Dthriftpy3=ON ..
  $ make
  $ cd thrift/lib/py3/test/gen-py3
  $ nosetests3 test/*.py

Result:

  ======================================================================
  FAIL: test_get_set (test.optional_mode.OptionalTests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File
  ".../fbthrift/_build/thrift/lib/py3/test/gen-py3/test/optional_mode.py",
  line 25, in test_get_set
      self.assertEquals(w.opt_field, None)
  AssertionError: 30 != None

  ----------------------------------------------------------------------
  Ran 162 tests in 0.336s

  FAILED (failures=1)

Most importantly 162 tests ran, the one failing test should be addressed
with its own fix.