thrift: Fix build error on OSS with Fedora
Summary:
Fix this error building on Fedora 30:

```
/home/foo/code/fb/fbthrift/thrift/lib/cpp2/async/RocketClientChannel.cpp:70:67:   required from here
/usr/include/fmt/core.h:349:40: error: static assertion failed: don't know how to format the type, include fmt/ostream.h if it provides an operator<< that should be used
  349 |   static_assert(no_formatter_error<T>::value,
      |                                        ^~~~~
make[2]: *** [thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/build.make:278: thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/async/RocketClientChannel.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:767: thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
```

Reviewed By: vitaut

Differential Revision: D22777856

fbshipit-source-id: a6242e91b5bd1db5fbaffee569defba36d09bd93