partition_manager - py3.11+ breaks asyncio.coroutine
Summary:
All new partition_manager builds are broken with the below error since D71332720 landed.  Seems like we can fix it by wrapping non-async functions...

```
INFO 2025-03-20 19:17:12.714 dba.partitions.manager: Using ods tag dba.partitions.roomba_partitions
WARNING 2025-03-20 19:17:12.717 dba.partitions.manager: Configerator updated dba/partitions/roomba_partitions
WARNING 2025-03-20 19:17:12.718 dba.partitions.manager: Configerator updated dba/partitions/config
WARNING 2025-03-20 19:17:12.719 dba.partitions.job_producer: Created 0 jobs
ERROR 2025-03-20 19:17:29.077 thrift.server.TAsyncioServer: Exception while processing request: module 'asyncio' has no attribute 'coroutine'
ERROR 2025-03-20 19:17:29.083 thrift.server.TAsyncioServer: Traceback (most recent call last):
  File "thrift/server/TAsyncioServer.py", line 180, in message_received
    await self.processor.process(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "thrift/util/Decorators.py", line 78, in nested
    ret = self.callFunction(name, seqid, iprot, oprot, server_ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "thrift/Thrift.py", line 161, in callFunction
    return process_fn(self, seqid, iprot, oprot, server_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "thrift/util/Decorators.py", line 158, in nested
    return func(self, args, handler_ctx, seqid, oprot, fn_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fb303_asyncio/fb303_core/BaseService.py", line 4195, in process_getRegexCounters
    fut = call_as_future(self._handler.getRegexCounters, self._loop, args.regex)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "thrift/util/asyncio.py", line 109, in call_as_future
    f = asyncio.coroutine(f)
        ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```

Reviewed By: yfeldblum

Differential Revision: D71664641

fbshipit-source-id: ce348947ef0c9995454c7863b943037626d2a1bb