Fix a format string
Summary:
Theres is an unescaped `{` in a format string which is caught by a newly introduced compile time checks:

```
thrift/lib/cpp2/util/DebugString.cpp:529:25: error: call to consteval function 'fmt::basic_format_string<char, folly::Range<const char *> &>::basic_format_string<char [26], 0>' is not a constant
expression
            fmt::format("Expected struct '{' at {}", tok));
                        ^
```

Fix it.

Reviewed By: jurmarcus

Differential Revision: D33924867

fbshipit-source-id: cbce42fa1f194a90dfa34b3f394e685d9e1d4fc0