Fix gcc build failure in thrift/test/fatal_serialization_test.cpp
Summary:
[Thrift] Fix gcc build failure in `thrift/test/fatal_serialization_test.cpp`.

```
thrift/test/fatal_serialization_test.cpp: In instantiation of 'void test_cpp2::simple_cpp_reflection::MultiProtocolTest_test_serialization_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = apache::thrift::test::RWPair<apache::thrift::SimpleJSONProtocolReader, apache::thrift::SimpleJSONProtocolWriter, true>]':
thrift/test/fatal_serialization_test.cpp:94:1:   required from here
thrift/test/fatal_serialization_test.cpp:99:7: error: missing braces around initializer for 'std::binary_function<int, int, bool>' [-Werror=missing-braces]
thrift/test/fatal_serialization_test.cpp:99:7: error: missing braces around initializer for 'std::binary_function<int, int, bool>' [-Werror=missing-braces]
```

Reviewed By: vitaut

Differential Revision: D16686176

fbshipit-source-id: e14c654c89b5877cd5a1504a2c77cd67747c4bb3