Fix missing `#include <fstream>` (#513)
Summary:
Without this, the build fails with

    error: implicit instantiation of undefined template 'std::basic_ifstream<char>'

Seen while building for Homebrew on macOS 12 at Homebrew/homebrew-core#108112.

The exact error is at https://github.com/Homebrew/homebrew-core/runs/7851989570?check_suite_focus=true#step:6:358.

Closes https://github.com/facebook/fbthrift/issues/512

Pull Request resolved: https://github.com/facebook/fbthrift/pull/513

Reviewed By: Mizuchi

Differential Revision: D38742189

Pulled By: vitaut

fbshipit-source-id: 6309074945fe4f0b08f038f2bfcdb066248982fe